### ISSUE TITLE
Inconsistency in command-line interface related to mdriztab=True

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1739] opened 2024-02-15 21:55 UTC
_Issue [HLA-1209](https://jira.stsci.edu/browse/HLA-1209) was created on JIRA by [Steve Goldman](https://jira.stsci.edu/secure/ViewProfile.jspa?name=sgoldman):_

Testing of the use of AstroDrizzle() for single_visit mosaic generation uncovered a use-case where setting 'mdriztab=True' caused other parameters set on the command line to be ignored; specifically, final_rot. This needs to be sorted out, since any user-specified parameter MUST take precedent at all times.

**Comment by stscijgbot-hstdp** [comment] 2024-03-06 22:00
_Comment by [Steve Goldman](https://jira.stsci.edu/secure/ViewProfile.jspa?name=sgoldman) on [JIRA](https://jira.stsci.edu/browse/HLA-1209?focusedCommentId=687342#comment-687342):_

This issue was recently raised again in a helpdesk ticket [INC0198393](https://stsci.service-now.com/nav_to.do?uri=incident.do%3Fsys_id=a3a9a07797280e5023a2fe971153af65%26sysparm_stack=incident_list.do%3Fsysparm_query=active=true). It's unclear when the issue arose, or whether this has always been a problem. Most of the related files don't seem to have been updated in at least the last 5 years. 

The critical code is [line 131](https://github.com/spacetelescope/drizzlepac/blob/57d52ad007a95cfcfc34858e9ef26df46a8f0f52/drizzlepac/processInput.py#L131) of processInput.py where user values are merged with mdriztab default values. Since the mdriz file (which hasn't been updated recently) has a default value for final_rot of {_}None{_}, the user value is being replaced by {_}None{_}. 

There is a comment in the code there stating:


```
    # interpret MDRIZTAB, if specified, and update configObj accordingly
    # This can be done here because MDRIZTAB does not include values for
    # input, output, or updatewcs.```

**Comment by mcara** [comment] 2024-03-07 08:20
Maybe @mackjenn can remember how `MDRIZTAB` was intended to be used. I very vaguely recall some discussions around `MDRIZTAB` (> 5 years ago). It could be that the code actually works as intended (`MDRIZTAB` overrides user input - it could be what INS wanted) but `MDRIZTAB` should not have had custom WCS parameters: obviously these are not intended to be used in the pipeline. So, either the logic in the code is buggy or the MDRIZTAB file contains fields that it was not supposed to have.

For now, users can load `MDRIZTAB` and delete parameters that they supply as input to astrodrizzle:

```python
from drizzlepac.mdzhandler import getMdriztabParameters
mdrztab = getMdriztabParameters(['file_name1_flc.fits'])
param_to_del = [
    'final_wcs',
    'final_outnx',
    'final_outny'
]
for k in param_to_del:
    del mdrztab[k]
AstroDrizzle(
    input,
    mdriztab=False,
    configobj=mdrztab,
    final_wcs=True,
    final_outnx=1111,
    final_outny=2222
)
```

**Comment by s-goldman** [comment] 2024-03-07 17:31
Thanks Mihai, this is really helpful. Unfortunately, it looks like deleting the parameters results in those parameters no longer being recognized as viable user inputs. That being said, I think I can find a fix along these lines using `getMdriztabParameters`.  Thanks!

**Comment by s-goldman** [comment] 2024-03-07 19:08
A possible solution is something like the following, however, there seem to be some issues with the result. Still investigating. 

```
from stsci.tools import teal
from drizzlepac.mdzhandler import getMdriztabParameters

configObj = configobj = teal.load("astrodrizzle")
configObj["mdrztab"] = getMdriztabParameters(["j96001cdq_flt.fits"])

input_flts = [
    "j96001cfq_flt.fits",
    "j96001cdq_flt.fits",
    "j96001cgq_flt.fits",
    "j96001ciq_flt.fits",
    "j96001clq_flt.fits",
    "j96001cjq_flt.fits",
    "j96001cmq_flt.fits",
    "j96001coq_flt.fits",
]

configObj["input"] = input_flts
configObj["output"] = "SUMMED_test"

configObj["mdrztab"]["driz_cr_corr"] = True
configObj["mdrztab"]["final_refimage"] = "hlsp_hlf_hst_wfc3-60mas_goodss_f275w_v2.0_conv_sci.fits"
configObj["mdrztab"]["final_rot"] = -35
configObj["mdrztab"]["final_outnx"] = 10000
configObj["mdrztab"]["final_outny"] = 10000

configObj["STEP 7a: CUSTOM WCS FOR FINAL OUTPUT"]["final_wcs"] = True


astrodrizzle.AstroDrizzle(
    configobj=configObj,
)
```

**Comment by stscijgbot-hstdp** [comment] 2024-03-13 18:35
_Comment by [Steve Goldman](https://jira.stsci.edu/secure/ViewProfile.jspa?name=sgoldman) on [JIRA](https://jira.stsci.edu/browse/HLA-1209?focusedCommentId=688627#comment-688627):_

After discussing this with Warren, it looks like the desired outcome is still being produced. The mdriztab=True options is resulting in the best pipeline options being passed to the configobj. The problem is that, while the mdriztab pipeline parameters should supersede the user's parameters, there should be a warning to the user that this is happening.

**Comment by mcara** [comment] 2024-03-13 19:06
> The mdriztab=True option is resulting in the best pipeline parameters being passed to the configobj.

**Comment by mcara** [comment] 2024-03-13 19:12
> The mdriztab=True option is resulting in the best pipeline parameters being passed to the configobj.

I have to disagree with this: the best parameters are the once that user wants. And those seem to be ignored. For the very least there has to be a workaround developed for the users.

**Comment by s-goldman** [comment] 2024-03-13 20:02
> > The mdriztab=True option is resulting in the best pipeline parameters being passed to the configobj.
> 
> I have to disagree with this: the best parameters are the ones that user wants. And those seem to be ignored. For the very least there has to be a workaround developed for the users.

I think you're right. This isn't the way it SHOULD work. I should have written above that this was the "previously" desired outcome. That being said, I'm not sure how common of an issue this is, and whether it's worth changing the way that the configuration parameters are merged. I will ping some of the other drizzling folks to see if the juice is worth the squeeze.

**Comment by mcara** [comment] 2024-03-13 20:11
Most likely users do not even realize that their options are ignored and simply move on with processing. Pipeline is probably using `mdriztab` exclusively. So, allowing users to overwrite some of the parameters loaded from `mdriztab` would be the right thing to do, IMO.

And if you want to keep the existing behavior, I think that the warning mentioned in a previous message should be upgraded to an exception to force users remove their custom parameters: `mdriztab` must be used exclusively; no user parameters allowed. + provide an example with a workaround.

**Comment by s-goldman** [comment] 2024-03-13 20:17
I totally agree. Good call 👍

**Comment by mackjenn** [comment] 2024-03-13 20:38
Chiming in here... I agree with Mihai.  The desired behavior is for the user to be able to use the MDRIZTAB default values as a starting point and then allow for any changes to those parameters from the command line.   

For example, final_rot=INDEF in the MDRIZTAB, but you should be able to override this by setting final_rot=0 to drizzle north up, while retaining the other recommended values for each instrument.

**Comment by stscijgbot-hstdp** [comment] 2024-03-19 18:25
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-1209?focusedCommentId=689389#comment-689389):_

As indicated, messages need to issued so the user is informed.

I will note that the logic here is not typical though there may be other issues at play. Under most circumstances, any values supplied on the command line as a direct parameter or as part of a file which is a direct parameter to a task should supersede any configuration values read by default by the task.

At the least this needs to be well-documented.  We can talk about this, but perhaps it should just be fixed according to expectation.

**Comment by stscijgbot-hstdp** [comment] 2024-03-19 18:35
_Comment by [Steve Goldman](https://jira.stsci.edu/secure/ViewProfile.jspa?name=sgoldman) on [JIRA](https://jira.stsci.edu/browse/HLA-1209?focusedCommentId=689397#comment-689397):_

[Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) After some discussions elsewhere including the github [issue 1739](https://github.com/spacetelescope/drizzlepac/issues/1739), I think it was unanimous by the instrument scientists (and Mihai) that the user inputs should supersede the mdriztab defaults. I have a PR that should do the trick, and I am testing that now.

**Closed** 2024-04-03 13:39 UTC

**Comment by stscijgbot-hstdp** [comment] 2024-04-03 13:40
_Comment by [Steve Goldman](https://jira.stsci.edu/secure/ViewProfile.jspa?name=sgoldman) on [JIRA](https://jira.stsci.edu/browse/HLA-1209?focusedCommentId=692355#comment-692355):_

closed by [#&#x2060;1774](https://github.com/spacetelescope/drizzlepac/pull/1774)
