### ISSUE TITLE
[EXP] Switching pandokia tests to Python 3

### ISSUE THREAD

**Issue by pllim** [spacetelescope/drizzlepac#73] opened 2017-07-13 16:27 UTC
Any insight on why some `drizzlepac` tests would fail in Python 3? For example, see https://ssb.stsci.edu/pandokia/pandokia.cgi?query=summary&qid=3142

**Comment by pllim** [comment] 2017-07-13 16:29
Also, 9 tests did not even make it to the report, likely because the test scripts themselves are not Python 3 compatible. Compare with a Python 2 log (e.g., https://ssb.stsci.edu/pandokia/pandokia.cgi?query=summary&qid=3143) to see which are missing.

**Comment by mcara** [comment] 2017-07-13 20:13
@pllim wrote:
> Any insight on why some drizzlepac tests would fail in Python 3?

I do not know exactly why they fail, and I do not know who and how moved these tests to Python 3 (and no one notified me about this). Looking at the ``wfc3_binned_asn`` test, I can see:

```
 fitsdiff: 3.0.dev19626
 a: wfc3_binned_asn_drz.fits
 b: reference.fits
 Keyword(s) not to be compared:
  DATE FILENAME FITSDATE HISTORY IRAF-TLM ORIGIN PROD_VER PYWCSVER
  RULEFILE UPWCSVER UPWTIM WCSCDATE
 Maximum number of different data values to be reported: 10
 Relative tolerance: 0.0, Absolute tolerance: 0.0

Primary HDU:

   Headers contain differences:
     Keyword D001ISCL has different values:
        a> 0.1188600026071072
        b> 0.11886
     Keyword D001SCAL has different values:
        a> 0.1188600026071072
        b> 0.11886
     Keyword D002ISCL has different values:
        a> 0.1188600026071072
        b> 0.11886
....................
```
indicating that the reference files did not store all the digits in the header. Why is that? I don't know. It is also possible that whomever ported tests to Python 3 did not get the correct reference files (i.e., copied references from OSX to be used on Linux tests).

**Comment by pllim** [comment] 2017-07-13 20:16
The port to Python 3 is currently experimental. I think all @jhunkeler did was switch the version of pandokia used without changing any files (but he can confirm). In addition, the port to Python 3 is inevitable and driven by Astropy's decision to drop Python 2 support soon (in a few months on dev), which would result in dev tests being unable to run in Python 2 anymore. This especially affects drizzlepac because it uses Astropy.

**Comment by mcara** [comment] 2017-07-13 20:20
> In addition, the port to Python 3 is inevitable...

That's fine.

**Comment by nden** [comment] 2017-07-13 20:21
While it's true that astropy is dropping support for python 2.0, does this mean that the astropy code will not work with python 2.0. ? In other words, is compatibility code going to be removed from astropy?  Even then I'm not sure that astropy.wcs has any 2.0 compatibility code. 
In addition, OPS is running this code in python 3, right? Just saying ... 
"DON"T PANIC"

**Comment by pllim** [comment] 2017-07-13 20:26
> is compatibility code going to be removed from astropy?

Yes. People seem pretty excited about sprinting at that actually...

And yes, I realize OPUS has not panicked yet and they run in Python 3 now. What is a concern here is not the software, but the *tests* running on pandokia.

So, yes, don't panic, but also don't forget. 😉

**Comment by larrybradley** [comment] 2017-07-13 20:31
Yes, the plan is remove all of the python 2.x compatibility.  However, I think the plan is to delay this until closer to the `Astropy 3.0` release (I *think* Erik said this in an email -- trying to find it).  This was intended to hold back the rush of expected PRs removing python 2.x stuff right after `Astropy 2.0` was released.

**Comment by mcara** [comment] 2017-07-13 20:38
> Yes, the plan is remove all of the python 2.x compatibility.

What does this mean? Will we comb existing code and intentionally make it not run on Python 2?

**Comment by larrybradley** [comment] 2017-07-13 20:49
The effect will be that some functionality no longer works in Python 2.  All of the `six` compatibility stuff is sure to go.  And any `Python 2.x`-specific workarounds will go too.  I'm sure some code will still work fine under Python 2, but it will no longer be tested against Python 2.

**Comment by pllim** [comment] 2017-07-13 20:57
No, I don't think we should remove Python 2 stuff here yet. But we need to make sure stuff (like the tests) would run in Python 3 as well.

**Comment by larrybradley** [comment] 2017-07-13 20:58
To be clear, I was referring to removing Python 2.x stuff from Astropy only.

**Comment by mcara** [comment] 2017-07-13 21:02
> To be clear, I was referring to removing Python 2.x stuff from Astropy.

Phew! @pllim said: _"People seem pretty excited about sprinting at that actually..."_ What a relief...

**Comment by pllim** [comment] 2017-07-14 13:45
I mean "Astropy people". Sorry for the confusion. Still, please make drizzlepac regression tests work with Python 3.

**Comment by nden** [comment] 2017-07-14 14:14
@pllim Why?

**Comment by pllim** [comment] 2017-07-14 14:23
Because pandokia uses `astropy.io.fits` for `diff`. If Astropy won't run in Python 2, that means pandokia also won't run in Python 2 (in dev sooner than public). If we can switch to Jenkins in time, you can configure your tests to only run in Python 2 with `astropy<3` (though I frown upon such practice) but the switch to Jenkins is another battle altogether.

**Comment by nden** [comment] 2017-07-14 14:28
I don't think there's a question of whether they should use 2 or 3. I think they should run under and with python 3. However we are moving to Jenkins and will have to rewrite the tests for Jenkins. Do we have to do the work twice - change pandokia tests, then rewrite them again for Jenkins. Do you know more than I do :-)?

**Comment by pllim** [comment] 2017-07-14 14:33
I foresee that switching to Jenkins would take much longer than switching to Python 3. Realistically, it won't happen before pandokia breaks in Python 2 because of Astropy.

This is because currently our pandokia tests are written as a pandokia-specific Python or XML scripts. You cannot simply copy-and-paste that into Jenkins environment; hence a complete re-write. In addition, you will also have to move the tests back into package repo (not in SVN purgatory) and write your own Jenkins test matrix (or at least customize from some template).

**Comment by pllim** [comment] 2017-07-31 19:39
Back to the tests in question for Python 3... I fixed a "print statement" in "test_driz.py", which hopefully will take care of the missing tests.

As for why file comparisons are failing for 14 tests, nothing obvious jumped out to me but I am not a drizzlepac expert. Could it simply be that the tests are too sensitive? Below is an example for "betadrizzle/acs/wfc/acs_tweak/test.py":

Python 2:
https://ssb.stsci.edu/pandokia/pandokia.cgi?query=detail&key_id=107200116 (report)
https://ssb.stsci.edu/steuermann/steuermann.cgi?action=log&name=conda_tests_2017-07-30-10:30:02/nott:conda_testing/dev_tests (back-end log)

Python 3:
https://ssb.stsci.edu/pandokia/pandokia.cgi?query=detail&key_id=107201182 (report)
https://ssb.stsci.edu/steuermann/steuermann.cgi?action=log&name=conda_tests_py3_2017-07-30-18:00:03/nott:conda_testing3/dev_tests (back-end log)

For example, when I simply create a WCS object from the Extension 1 header of one of the output (of another test with similar failure), my WCS values (the last few decimals) do not agree with both Python 2 nor 3 results!

**Comment by pllim** [comment] 2017-08-04 14:12
In addition to above, the following tests are incompatible with Python 3 also. I fixed a couple of obvious offending code (print statement, xrange) but they still fail:

https://ssb.stsci.edu/pandokia/pandokia.cgi?query=summary&qid=3860

```
Log:
  File "/srv/iraf/bldtmp/prCz/p/envs/dev/lib/python3.5/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/srv/iraf/bldtmp/prCz/p/envs/dev/lib/python3.5/unittest/case.py", line 601, in run
    testMethod()
  File "/srv/iraf/bldtmp/prCz/p/envs/dev/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/srv/rt/betadrizzle/unit/test_driz.py", line 427, in test_gaussian_with_grid
    insci = self.make_grid_image(insci, 64, 100.0)
  File "/srv/rt/betadrizzle/unit/test_driz.py", line 200, in make_grid_image
    for y in range(spacing/2, shape[0], spacing):
None
```

**Comment by mcara** [comment] 2017-08-04 14:16
I have fixed your fixes in a yesterday commit that should take care of this (assuming you did not overwrite my commit).

```python
for y in range(spacing/2, shape[0], spacing):
```
should be 
```python 
for y in range(spacing//2, shape[0], spacing):
```

**Comment by pllim** [comment] 2017-09-28 15:47
@mcara , we turned off Python 2 testing on pandokia (mainly because astropy dev removed Python 2 support), so now some tests are failing because results are a bit different in Python 3. However, this does not mean we can stop supporting Python 2 here (we just cannot use astropy>=3 with it). How do you plan to address the result difference?

**Comment by mcara** [comment] 2017-09-28 16:15
Why do we update astropy to v3 in our Python 2 releases? Cannot we freeze astropy to <3 for Python 2?

**Comment by mcara** [comment] 2017-09-28 16:26
@pllim By the way, I just looked at test logs and I think that all of them can be okified. Do you want to do it yourself or I can do it later tonight. (Just let me know if you do it)

**Comment by pllim** [comment] 2017-09-28 16:28
> Why do we update astropy to v3 in our Python 2 releases?

We don't. Our releases is not specific to Python 2 or 3. They are supposed to work on both. All I am saying is that if people having Python 2, they shouldn't be using `astropy>=3`, which has nothing to do with `drizzlepac` itself.

@mcara , please okify them when you have the chance. They are all yours. 😄

**Comment by mcara** [comment] 2017-09-29 02:50
@pllim OKified

**Closed** 2017-09-29 13:31 UTC
