### ISSUE TITLE
TweakReg crashing trying to create undistorted ref_wcs from already undistorted image

### ISSUE THREAD

**Issue by Vb2341** [spacetelescope/drizzlepac#92] opened 2017-10-27 17:48 UTC
Tweakreg is crashing with the following Traceback: 
```Traceback (most recent call last):
  File "/user/vbajaj/anaconda2/envs/astroconda/lib/python2.7/site-packages/drizzlepac/util.py", line 219, in wrapper
    func(*args, **kwargs)
  File "/user/vbajaj/anaconda2/envs/astroconda/lib/python2.7/site-packages/drizzlepac/tweakreg.py", line 373, in run
    cat_origin=cat_src, **kwargs)
  File "/user/vbajaj/anaconda2/envs/astroconda/lib/python2.7/site-packages/drizzlepac/imgclasses.py", line 1120, in __init__
    self.wcs = utils.output_wcs([self.wcs], undistort=True)
  File "/user/vbajaj/anaconda2/envs/astroconda/lib/python2.7/site-packages/stwcs/distortion/utils.py", line 44, in output_wcs
    outwcs = make_orthogonal_cd(ref_wcs)
  File "/user/vbajaj/anaconda2/envs/astroconda/lib/python2.7/site-packages/stwcs/distortion/utils.py", line 126, in make_orthogonal_cd
    scale = (wcs.idcscale) / 3600.  # HST pixel scale provided
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
```

The input image is an undistorted (UVIS drc) image, and the images are being aligned to an already existing reference catalog.  From what I can tell, it's crashing because it can't find the value of the idcscale attribute for the reference WCS.  Since I am aligning to an external catalog, I believe the reference WCS is just the WCS read from the first image in the input image list.  However, the input image list is all drc files, so they are undistorted and therefore have wcs.idcscale = None.

However, this only happens when I run tweakreg on an image that I have **already** tweaked once before.  If I just pick a "fresh" drizzled image and run it, I get no issues.  Specifically, I have to already have had to run tweakreg using the ```fitgeometry='general'``` to get this error.  If tweakreg was previously run using ```fitgeometry='rscale'```, this does **not** happen

I _think_ this is might come from an issue with an issue in drizzlepac/imgclasses.py, specifically line 1114: 
```          if _is_wcs_distorted(self.wcs):
                    if self.wcs.instrument == 'DEFAULT':
                        raise ValueError("Distorted non-HST reference images "
                                         "are not supported.")
                    log.warn("\nReference image contains a distorted WCS.\n"
                             "Using the undistorted version of this WCS.\n")
                    self.wcs = utils.output_wcs([self.wcs], undistort=True)
```

I think the check ```_is_cd_unitary(wcs)``` within ```_is_wcs_distorted``` is the issue here.  I figure the current distortion solution does not fully account for axis-dependent scale and rotation.  When TweakReg is run with a high fidelity catalog to align the images (GAIA), xrot, yrot, xscale, and yscale get applied to the CD matrix.  My understanding of the linear algebra isn't too great, but I figure this makes the matrix non-unitary, causing TweakReg to detect the image as 'distorted'.  Im not sure what the best way forward is, because I guess the images are _technically_ distorted (or the pixels arent square at least?), but I'm not sure if that should really matter in terms of using this WCS as a reference for other alignments.

**Comment by mcara** [comment] 2017-10-30 08:10
I think there are several points to discuss here but in the end I feel that there is something wrong with your workflow as I cannot justify the need for doing what apparently you are trying to do (well, without me understanding the whole problem that you are trying to solve). Let me start with the last part of your message:

> _... I guess the images are technically distorted (or the pixels arent square at least?), but I'm not sure if that should really matter in terms of using this WCS as a reference for other alignments._

First of all, the above sentence contradicts your first sentence:

> _The input image is an **undistorted** (UVIS drc) image..._

Only the first cited sentence is correct: your reference image **is distorted** (i.e., axes are not orthogonal or scales are not equal) and tweakreg was designed to work either with "un-distorted" reference WCS (orthogonal axes, no SIP, etc.) or a standard HST "FLT"-like image that we know how to un-distort. A long time ago a decision was made not to support distorted non-HST images (because we do not know how are distortions represented in arbitrary images) - see some comments here: https://trac.stsci.edu/ssb/stsci_python/ticket/1158.

Without diving into the math used for alignment, my gut feeling is that in principle it should be possible to support "distorted" WCS whose distortion is limited *exclusively* to linear terms. However, this may require some serious testing of the code to make sure it works correctly and I doubt we will have time for this. In addition, this seems to me *completely* unnecessary/useless. [Moreover, after I introduced `_is_wcs_distorted()` testing into the code, it quickly revealed a serious bug in astrodrizzle that resulted in astrodrizzle producing skewed WCS - so this is an important check of sanity for most common use of tweakreg and I would not want to turn it off.] Let me explain this point (why it is not necessary to support distorted/skewed WCS).

A reference WCS essentially defines a tangent plane (to the celestial sphere) in which alignment and "comparison" between positions of image and reference sources will be performed. This reference WCS in principle does not need to have orthogonal axes but there is no loss of generality if we require that WCS be "un-distorted" - we will still be able to perform an alignment just as good as with a skewed reference WCS: there is no advantage of using a skewed WCS. It is *critically important* to understand that alignment is performed by comparing coordinates of image sources to the reference sources and that the reference tangent plane is just a "medium" for this comparison.

So, if you *really really want* to align drizzled images to an external catalog *twice* then you should provide a reference image that is not distorted. For example, keep a copy of one of your drizzled images and rename it to something like `'reference.fits'` and use it for all your `tweakreg` runs. Keep in mind that in this case your reference catalog should be provided either in world coordinates or in image coordinates of this `'reference.fits'` image. Assuming it is a GAIA catalog, probably it is already provided in world coordinates.

> I figure the current distortion solution does not fully account for axis-dependent scale and rotation. When TweakReg is run with a high fidelity catalog to align the images (GAIA), xrot, yrot, xscale, and yscale get applied to the CD matrix.

Just to make it clear here: tweakreg should be able to find alignments/WCS corrections using specified fit geometry (`'shift'`, `'rscale'`, or `'general'`). I think what you mean here is that not the `tweakreg` is the problem but rather the quality of STScI-produced distortion model described through IDCTAB. That may very well be...

-----

### Workarounds:

1. As suggested above, create a valid undistorted reference image by making a copy (e.g., `'reference.fits'`) of one original drizzled image without aligning it using `tweakreg`. Provide this `'reference.fits'` as a reference image for all subsequent runs of `tweakreg`.

2. Add `'IDCSCALE'` keyword to the headers of your drizzled images and set it to the value in the original FLT images. I never tried this before but it may work if you are lucky enough.

3. Best solution is to modify your workflow if you know that GAIA is a better catalog:

    1. If there are enough "good" sources (with high S/N detection levels) in your FLT images - align *those* FLT images directly to your reference catalog and *only then* drizzle them. This way you will obtain *rectified* (orthogonal axes & equal scales) drizzled images which are also aligned to your preferred catalog.

    2. If S/N is low in FLT images, then drizzle them to obtain a higher S/N image. align it (once) to to GAIA catalog using tweakreg, and then correct FLT image's WCS using `blot`.

4. It is not clear why it is necessary to run tweakreg twice (or more)... Do you align drizzled images to some "first reference catalog" and then you want to align them to a second reference catalog (GAIA)? If so - I do not see the point of doing this. On the other hand, if you are simply re-running `tweakreg` on the same images and reference catalog using different `fitgeometry` parameters, source finding parameters, matching parameters, etc., then the simplest solution of all would be to set `updatehdr` to `False` and turn `updatehdr` on only when you are satisfied with the obtained solution.

**Comment by Vb2341** [comment] 2017-11-14 21:13
I think you are correct in saying that the issue lies moreso within the IDCTAB rather than tweakreg.  If the IDCTAB accounted for the residual linear terms, this problem wouldn't exist.

Anyway, the crashing is limiting to a workflow in which we initially align _one_ image to Gaia and then the other images to the first.  This is actually a fairly standard procedure.  Generally, HST images can detect many more sources than Gaia, and on the flip side, many of the low-error Gaia sources are saturated in HST images (esp wide band filters with long exposures).  We are finding that, in some cases, aligning to Gaia at first can provide a good coarse solution (and remove the residual skew, which otherwise makes large mosaicks impossible to create).   However, we can then give a very small search radius, and then align the images to each other for a higher quality fit (due to the increased number of sources that can be matched between two HST images).

This can be applied a workflow Jennifer Mack is experimenting with, specifically for mosaicking, where the tiles of the mosaics are initially aligned to Gaia for a 'coarse' alignment, and then aligned to each other to get a higher quality fit. 

To address workaround 4:
In most cases, I know Jennifer and I always run TweakReg with updatehdr = True, as we often have parameters that perform well with most of the data, and then only have to go back and adjust them for those with poor fits, this saves a lot of time when working with many images, and makes it possible to do visual checks of alignment with software like ds9.  

I guess I'm just wondering, if TweakReg has the capability to change the CD matrix to make the image fail the ```_is_wcs_distorted()``` check, and knows that the image is still an HST image, would it be possible to throw a warning rather than raise an exception in this case?  The distortion that it's detecting in this case is fully representable without needing to look up parameters from an IDCTAB as the distortion is still part of the linear terms (and so I think attempting to do what you've suggested in workaround 2 isn't applicable, plus I figure it will start looking for all the other IDCTAB related keywords, which shouldn't be applied to the drizzled images).

**Comment by mcara** [comment] 2017-11-15 00:02
I just got off the phone with Jennifer. I still do not think there is need allow tweakreg to use distorted images.

Here is my understanding of what your workflow currently is (at least the one that crashes):

1. For a given visit - align FLT images using `tweakreg`;
2. Drizzle aligned images;
3. Repeat 1. and 2. for all visits. This will produce drizzled images: `im1_drz.fits`, `im2_drz.fits`, `im3_drz.fits`, ...
4. Align each drizzled image to Gaia catalog. This will "tweak" the WCS of the previously drizled images introducing a skew into their CD matrix. I assume Gaia catalog is provided through the `refcat` parameter.
5. Now you want to run tweakreg again on these aligned images by passing a list of (let's say 20) drizzled images `im1_drz.fits`, `im2_drz.fits`, `im3_drz.fits`, ... In this case `tweakreg` will take the first image and use it as both: i) source for the reference catalog, and ii) source of the reference WCS that defines the tangent plane. However, because this WCS has a skew `tweakreg` crashes.

I just want to re-iterate that *reference WCS* is used exclusively for the definition of the tangent plane (it indicates the tangent point on the sphere) and **it is not used** for alignment (in general). That is, you should not worry if your reference image is somehow slightly "misaligned" or that it was obtained from an image with IDCTAB errors.

Let me show how your workflow should be modified so that it works with current `tweakreg` and it actually is more explicit in how it uses WCS and reference *catalogs*:

1. For a given visit - align FLT images using `tweakreg`;
2. Drizzle aligned images;
3. Repeat 1. and 2. for all visits. This will produce drizzled images: `im1_drz.fits`, `im2_drz.fits`, `im3_drz.fits`, ...
4. **[New]** Make a copy of `im1_drz.fits` and call it `reference.fits`.
5. **[Old]** Align each drizzled image to Gaia catalog. This will "tweak" the WCS of the previously drizled images introducing a skew into their CD matrix. I assume Gaia catalog is provided through the `refcat` parameter. **[New]:** Set `clean=False` [see next step] Also, you can provide `refimage` parameter and point to the `reference.fits` or just let `tweakreg` guess a tangent point (as it was doing before) - it does not matter here.
6. **[New]** Make a copy of the `im1_drz_sky_catalog.coo` (or similarly named) file produced by `tweakreg` in the previous step (or choose some other catalog to be a *reference catalog* for next step).
7. **[Modified Old Step 5]:** Set `input` to ~~`im1_drz.fits`~~, `im2_drz.fits`, `im3_drz.fits`, ...  [so align *all other images* except for the first]. Set `refimage=reference.fits` (from step 4). Set `refcat=im1_drz_sky_catalog.coo` from step 6.

I believe this should achieve what you want in a way that explicitly shows what is being aligned to what (reference catalog).

**Comment by stsci-hack** [comment] 2017-11-17 21:35
This scenario does not warrant any change to the code, due to the unorthodox use of the code being discussed. The initial fit to the external absolute reference frame will result in alignment that does not require any additional alignment, barring any systematic errors in the reference frame itself.  Therefore, I believe that the solutions provided by @mcara completely resolve the issue raised here.

**Comment by mcara** [comment] 2017-12-05 20:54
@Vb2341 Do you think we can close this issue?

**Closed** 2017-12-12 20:09 UTC
Labels: question
